name: IDP CI
on:
  push:
    branches:
      - main
env:
    AWS_REGION: us-east-1
    ECR_REPOSITORY: wrathlc_idp
    ECS_SERVICE: wrathlc-idp
    ECS_CLUSTER: wrathlc
    ECS_TASK_DEFINITION: aws-dev-idp-task-definition.json
    
    CONTAINER_NAME: wrathlc_idp 
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        environment: Release
        steps:
        - 
            name: Checkout
            uses: actions/checkout@v2
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
        -
            name: Build and Export Image
            uses: docker/build-push-action@v3
            with:
                context: .
                file: ./WrathLC.Identity.Idp/Dockerfile
                tags: wrathlc_idp:latest
                outputs: type=docker,dest=/tmp/wrathlc_idp.tar
                build-args: |
                    CONFIGURATION=Release
        -
            name: Upload Artifact
            uses: actions/upload-artifact@v3
            with:
                name: wrathlc_idp
                path: /tmp/wrathlc_idp.tar
    # approve:
        # name: Approve
        # runs-on: ubuntu-latest
        # needs: build
        # steps:
        # - name: Wait for Approval
          # uses: trstringer/manual-approval@v1
          # with:
            # secret: ${{ github.TOKEN }}
            # approvers: mfuqua3
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: build
        steps:
        - 
            name: Checkout
            uses: actions/checkout@v2
        - 
            name: Set Up Docker Buildx
            uses: docker/setup-buildx-action@v2
        -
            name: Download Artifact
            uses: actions/download-artifact@v3
            with:
                name: wrathlc_idp
                path: /tmp
        -
            name: Load Image
            run: |
                docker load --input /tmp/wrathlc_idp.tar
                docker image ls -a
        -
            name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
        -
            name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1
        -
            name: Tag and Push Image to Amazon ECR
            id: push-image
            env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                IMAGE_TAG: ${{ github.sha }}
            run: |
                docker tag wrathlc_idp:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        -
            name: Update Task Definition
            id: task-def
            uses: aws-actions/amazon-ecs-render-task-definition@v1
            with:
                task-definition: ${{ env.ECS_TASK_DEFINITION }}
                container-name: ${{ env.CONTAINER_NAME }}
                image: ${{ steps.push-image.outputs.image }}
                environment-variables: |
                    ${{ secrets.AWS_CONNECTION_STRING }}
                    ${{ secrets.DISCORD_SECRET }}
                    ${{ secrets.DEV_CLIENT_SECRET }}
        -
            name: Deploy Amazon ECS task definition
            uses: aws-actions/amazon-ecs-deploy-task-definition@v1
            with:
                task-definition: ${{ steps.task-def.outputs.task-definition }}
                service: ${{ env.ECS_SERVICE }}
                cluster: ${{ env.ECS_CLUSTER }}
                wait-for-service-stability: false
            
    
